import { SlashCommandBuilder, PermissionFlagsBits } from 'discord.js';
import { createEmbed, successEmbed, errorEmbed } from '../../utils/embeds.js';
import { InteractionHelper } from '../../utils/interactionHelper.js';
import { getAutomodConfig, saveAutomodConfig, getDefaultAutomodConfig } from '../../services/automodEngine.js';

const RULES = ['words','regex','invites','links','externalLinks','suspiciousLinks','linkSpam','duplicate','fastMessages','caps','mentionSpam','everyone','emojiSpam','zalgo','attachments','stickers','repeatedChars','messageLength'];
const ACTIONS = [{name:'delete',value:'delete'},{name:'warn + delete',value:'delete_warn'},{name:'timeout + delete',value:'delete_timeout'},{name:'timeout only',value:'timeout'},{name:'kick',value:'kick'},{name:'ban',value:'ban'}];
const data = new SlashCommandBuilder().setName('automod').setDescription('Configure the advanced AutoMod system.').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild)
.addSubcommand(s=>s.setName('enable').setDescription('Enable AutoMod.')).addSubcommand(s=>s.setName('disable').setDescription('Disable AutoMod.')).addSubcommand(s=>s.setName('status').setDescription('Show AutoMod configuration.'))
.addSubcommand(s=>s.setName('rule').setDescription('Enable/disable a rule and choose its action.').addStringOption(o=>o.setName('name').setDescription('Rule name').setRequired(true).addChoices(...RULES.map(r=>({name:r,value:r})))).addBooleanOption(o=>o.setName('enabled').setDescription('Whether enabled').setRequired(true)).addStringOption(o=>o.setName('action').setDescription('Action').setRequired(true).addChoices(...ACTIONS)))
.addSubcommand(s=>s.setName('word').setDescription('Add or remove a blocked word.').addStringOption(o=>o.setName('action').setDescription('Operation').setRequired(true).addChoices({name:'add',value:'add'},{name:'remove',value:'remove'})).addStringOption(o=>o.setName('word').setDescription('Word or phrase').setRequired(true)))
.addSubcommand(s=>s.setName('regex').setDescription('Add or remove a regex filter.').addStringOption(o=>o.setName('action').setDescription('Operation').setRequired(true).addChoices({name:'add',value:'add'},{name:'remove',value:'remove'})).addStringOption(o=>o.setName('pattern').setDescription('Regex pattern').setRequired(true)))
.addSubcommand(s=>s.setName('domain').setDescription('Allow or remove a link domain.').addStringOption(o=>o.setName('action').setDescription('Operation').setRequired(true).addChoices({name:'allow',value:'allow'},{name:'remove',value:'remove'})).addStringOption(o=>o.setName('domain').setDescription('Domain').setRequired(true)))
.addSubcommand(s=>s.setName('exempt').setDescription('Exempt a user, role, or channel.').addStringOption(o=>o.setName('action').setDescription('Operation').setRequired(true).addChoices({name:'add',value:'add'},{name:'remove',value:'remove'})).addStringOption(o=>o.setName('type').setDescription('Type').setRequired(true).addChoices({name:'user',value:'user'},{name:'role',value:'role'},{name:'channel',value:'channel'})).addStringOption(o=>o.setName('id').setDescription('ID').setRequired(true)))
.addSubcommand(s=>s.setName('gifonly').setDescription('Allow a user or role to send GIFs only.').addStringOption(o=>o.setName('action').setDescription('Operation').setRequired(true).addChoices({name:'add',value:'add'},{name:'remove',value:'remove'})).addStringOption(o=>o.setName('type').setDescription('Target').setRequired(true).addChoices({name:'user',value:'user'},{name:'role',value:'role'})).addStringOption(o=>o.setName('id').setDescription('ID').setRequired(true)))
.addSubcommand(s=>s.setName('logchannel').setDescription('Set or clear the AutoMod log channel.').addStringOption(o=>o.setName('channel').setDescription('Channel ID; omit to clear').setRequired(false)))
.addSubcommand(s=>s.setName('reset').setDescription('Reset AutoMod to safe defaults.'));

export default { data, category:'moderation', async execute(interaction,config,client){
 const sub=interaction.options.getSubcommand(), c=await getAutomodConfig(client,interaction.guildId);
 if(sub==='status')return InteractionHelper.universalReply(interaction,{embeds:[createEmbed({title:`AutoMod ${c.enabled?'Enabled':'Disabled'}`,description:`**Rules:** ${RULES.filter(r=>c.rules[r]?.enabled).length}/${RULES.length}\n**GIF-only users:** ${c.gifOnlyUsers.length}\n**GIF-only roles:** ${c.gifOnlyRoles.length}\n**Blocked words:** ${c.blockedWords.length}\n**Regex:** ${c.regexPatterns.length}\n**Allowed domains:** ${c.allowedDomains.length}\n**Log:** ${c.logChannelId?`<#${c.logChannelId}>`:'Not set'}`,color:c.enabled?'success':'warning'})]});
 if(sub==='enable'||sub==='disable'){c.enabled=sub==='enable';await saveAutomodConfig(client,interaction.guildId,c);return InteractionHelper.universalReply(interaction,{embeds:[successEmbed(`AutoMod ${c.enabled?'enabled':'disabled'}.`)]});}
 if(sub==='reset'){await saveAutomodConfig(client,interaction.guildId,getDefaultAutomodConfig());return InteractionHelper.universalReply(interaction,{embeds:[successEmbed('AutoMod reset to safe defaults and disabled.')]});}
 if(sub==='rule'){const n=interaction.options.getString('name');c.rules[n]={...(c.rules[n]||{}),enabled:interaction.options.getBoolean('enabled'),action:interaction.options.getString('action')};await saveAutomodConfig(client,interaction.guildId,c);return InteractionHelper.universalReply(interaction,{embeds:[successEmbed(`Rule **${n}** updated.`)]});}
 if(sub==='word'){const a=interaction.options.getString('action'),w=interaction.options.getString('word').trim();if(a==='add'&&!c.blockedWords.some(x=>x.toLowerCase()===w.toLowerCase()))c.blockedWords.push(w);if(a==='remove')c.blockedWords=c.blockedWords.filter(x=>x.toLowerCase()!==w.toLowerCase());await saveAutomodConfig(client,interaction.guildId,c);return InteractionHelper.universalReply(interaction,{embeds:[successEmbed(`Blocked word **${w}** ${a==='add'?'added':'removed'}.`)]});}
 if(sub==='regex'){const a=interaction.options.getString('action'),p=interaction.options.getString('pattern');try{new RegExp(p,'iu');}catch{return InteractionHelper.universalReply(interaction,{embeds:[errorEmbed('Invalid regex pattern.')]});}if(p.length>200)return InteractionHelper.universalReply(interaction,{embeds:[errorEmbed('Regex limited to 200 characters.')]});if(a==='add'&&!c.regexPatterns.includes(p))c.regexPatterns.push(p);if(a==='remove')c.regexPatterns=c.regexPatterns.filter(x=>x!==p);await saveAutomodConfig(client,interaction.guildId,c);return InteractionHelper.universalReply(interaction,{embeds:[successEmbed(`Regex ${a==='add'?'added':'removed'}.`)]});}
 if(sub==='domain'){const a=interaction.options.getString('action'),d=interaction.options.getString('domain').toLowerCase().replace(/^https?:\/\//,'').replace(/^www\./,'').split('/')[0];if(a==='allow'&&!c.allowedDomains.includes(d))c.allowedDomains.push(d);if(a==='remove')c.allowedDomains=c.allowedDomains.filter(x=>x!==d);await saveAutomodConfig(client,interaction.guildId,c);return InteractionHelper.universalReply(interaction,{embeds:[successEmbed(`Domain **${d}** ${a==='allow'?'allowed':'removed'}.`)]});}
 if(sub==='exempt'){const a=interaction.options.getString('action'),t=interaction.options.getString('type'),id=interaction.options.getString('id').replace(/[<@&#>]/g,''),k=t==='user'?'exemptUsers':t==='role'?'exemptRoles':'exemptChannels';if(a==='add'&&!c[k].includes(id))c[k].push(id);if(a==='remove')c[k]=c[k].filter(x=>x!==id);await saveAutomodConfig(client,interaction.guildId,c);return InteractionHelper.universalReply(interaction,{embeds:[successEmbed(`Exemption updated for **${t}**.`)]});}
 if(sub==='gifonly'){const a=interaction.options.getString('action'),t=interaction.options.getString('type'),id=interaction.options.getString('id').replace(/[<@&#>]/g,''),k=t==='user'?'gifOnlyUsers':'gifOnlyRoles';if(a==='add'&&!c[k].includes(id))c[k].push(id);if(a==='remove')c[k]=c[k].filter(x=>x!==id);await saveAutomodConfig(client,interaction.guildId,c);return InteractionHelper.universalReply(interaction,{embeds:[successEmbed(`GIF-only ${t} restriction ${a==='add'?'enabled':'removed'}.`)]});}
 if(sub==='logchannel'){c.logChannelId=interaction.options.getString('channel')?.replace(/[<#>]/g,'')||null;await saveAutomodConfig(client,interaction.guildId,c);return InteractionHelper.universalReply(interaction,{embeds:[successEmbed(c.logChannelId?`AutoMod logs set to <#${c.logChannelId}>.`:'AutoMod log channel cleared.')]});}
}};
